/**
 * Renders a schema.org JSON-LD block. Data is generated by us (never user input);
 * dangerouslySetInnerHTML is the standard, correct way to emit ld+json (React would
 * otherwise HTML-escape the JSON and break it).
 */
export function JsonLd({ data }: { readonly data: Record<string, unknown> }) {
  return (
    <script
      type="application/ld+json"
      dangerouslySetInnerHTML={{ __html: JSON.stringify(data) }}
    />
  );
}
